version: '3.7'
services:
  app:
    build: .
    container_name: bonfire-api-container
    ports: 
      - 5050:5050
      - 9222:9222
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local