name: NodeJS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Project checkout
    - uses: actions/checkout@v2
    
    - name: Use NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
      
    - name: Project build
      run: npm run build
      
  deploy-dev:
    name: Deploy development environment
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy
      run: echo 'Deploy dev
